name: hive_flutter
description: Extension for Hive. Utils for using Hive with Flutter.
version: 0.1.0
author: Simon Leier <simonleier@gmail.com>
homepage: https://github.com/leisim/hive

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  hive: ">=0.4.0 <1.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter